---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  interval: 30s
  path: ./flux
  prune: false
  serviceAccountName: instavote
  sourceRef:
    kind: GitRepository
    name: instavote-deploy

